language: cpp
os: linux
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cppcheck


script:
  # скрипт сборки и тестирования проекта:
#  - cmake -DCMAKE_CXX_COMPILER="g++-6" ..
#  - make
#  - ctest -T memcheck
  - mkdir build
  - cd build
  - cmake ../ -DCMAKE_BUILD_TYPE=Debug
  - cmake --build . --target Tests